### ISSUE TITLE
error 500 uploading user certificate when no CA is there

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/downloadservice#34]
this should make sure to produce a sentry message and also return something useful to the user

```python
>>> import ctadata
>>> cl = ctadata.api.APIClient()
>>> cl.upload_certificate("/tmp/x509up_u1000")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/savchenk/ctadata/ctadata/api.py", line 158, in upload_certificate
    raise CertificateError(r.text)
ctadata.api.CertificateError: <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>


```

```python
  File "/downloadservice/downloadservice/app.py", line 162, in decorated
    return f(user, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/downloadservice/downloadservice/app.py", line 190, in upload_cert
    cabundle = open(app.config['CTADS_CABUNDLE'], 'r').read()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/downloadservice-data/dcache_cabundle.pem'

```

**Comment by Ph0tonic** [comment]
I will fix this, thanks. By the way, the CABundle file should be uploaded first using :
```python
cl.upload_admin_certificate("/tmp/x509up_u1000", cabundle_file_path="your_cabundle_file")
```
