### ISSUE TITLE
proxy certificates can not be verified here

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/downloadservice#36]
it's not possible to verify proxy certificate which we need:

```python
>>> verify_certificate(open("ca.pem").read(), open("/tmp/x509up_u1000").read())
Traceback (most recent call last):
  File "/home/savchenk/downloadservice/downloadservice/certificate.py", line 31, in verify_certificate
    ctx.verify_certificate()
  File "/home/savchenk/miniconda-recent/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1968, in verify_certificate
    raise self._exception_from_context()
OpenSSL.crypto.X509StoreContextError: proxy certificates not allowed, please set the appropriate flag
```

Some adaptation is needed. Apparently these setups of openssl discriminate against them. We can try to add a test for them too.

https://www.openssl.org/docs/man3.0/man7/proxy-certificates.html

**Comment by volodymyrss** [comment]
still need a test
