### ISSUE TITLE
issue with chunks

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/downloadservice#69]
noticed by @andriineronov , with this client log:

```python
NFO:ctadata.api:uploaded 760.0 Mb
> INFO:ctadata.api:uploaded 770.0 Mb
> INFO:ctadata.api:uploaded 779.849775314331 Mb
> Traceback (most recent call last):
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 748, in _update_chunk_length
>      self.chunk_left = int(line, 16)
> ValueError: invalid literal for int() with base 16: b''
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 443, in _error_catcher
>      yield
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 815, in read_chunked
>      self._update_chunk_length()
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 752, in _update_chunk_length
>      raise InvalidChunkLength(self, line)
> urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>    File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 816, in generate
>      yield from self.raw.stream(chunk_size, decode_content=True)
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 623, in stream
>      for line in self.read_chunked(amt, decode_content=decode_content):
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 844, in read_chunked
>      self._original_response.close()
>    File "/opt/conda/lib/python3.9/contextlib.py", line 137, in __exit__
>      self.gen.throw(typ, value, traceback)
>    File "/opt/conda/lib/python3.9/site-packages/urllib3/response.py", line 460, in _error_catcher
>      raise ProtocolError("Connection broken: %r" % e, e)
> urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>    File "/opt/conda/bin/cta-data", line 8, in <module>
>      sys.exit(main())
>    File "/opt/conda/lib/python3.9/site-packages/ctadata/cli.py", line 56, in main
>      cli(obj={})
>    File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>      return self.main(*args, **kwargs)
>    File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
>      rv = self.invoke(ctx)
>    File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>      return _process_result(sub_ctx.command.invoke(sub_ctx))
>    File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>      return ctx.invoke(self.callback, **ctx.params)
>    File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>      return __callback(*args, **kwargs)
>    File "/opt/conda/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>      return f(get_current_context(), *args, **kwargs)
>    File "/opt/conda/lib/python3.9/site-packages/ctadata/cli.py", line 47, in put_path
>      ctx.obj['api'].upload_file(local_path, path)
>    File "/opt/conda/lib/python3.9/site-packages/ctadata/api.py", line 228, in upload_file
>      logger.error("error: %s", r.text)
>    File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 923, in text
>      if not self.content:
>    File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 899, in content
>      self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
>    File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 818, in generate
>      raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
>
```

Could be related:

https://ctao-ch-dc.sentry.io/issues/5317564828/?environment=production&project=4505709666762752&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1

**Comment by Ph0tonic** [comment]
I started to investigate this issue and tried to reproduce it.
However I haven't been able to do so yet. I tried to upload the same file as in sentry on staging but it worked without any issue.

The issues is however related to the migration to the production server by using cheroot. For some reasons, cheroot sometime fails when uploading chunked files. It seems to be related to the http protocol but I am still not sure where this comes from. Temporarily, I rolled back the services to not use the prod server.

I will continue to investigate and report any progress here.
